//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CineMatinee001Entities4 : DbContext
    {
        public CineMatinee001Entities4()
            : base("name=CineMatinee001Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cartelera> Cartelera { get; set; }
        public DbSet<Cuadre> Cuadre { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Empleado_> Empleado_ { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<Facturacion> Facturacion { get; set; }
        public DbSet<Funcion> Funcion { get; set; }
        public DbSet<Horario_empleado> Horario_empleado { get; set; }
        public DbSet<Nomina_rrhh> Nomina_rrhh { get; set; }
        public DbSet<Sexo> Sexo { get; set; }
        public DbSet<User> User { get; set; }
    
        public virtual int ERegCartelera(Nullable<System.DateTime> fechareg, Nullable<int> id_funcion, Nullable<int> id_sala, string descripcion_pelicula, Nullable<System.DateTime> fechaDispIni, Nullable<System.DateTime> fechaDispFin, Nullable<double> precio_unit, Nullable<int> noReg_Cartelera)
        {
            var fecharegParameter = fechareg.HasValue ?
                new ObjectParameter("Fechareg", fechareg) :
                new ObjectParameter("Fechareg", typeof(System.DateTime));
    
            var id_funcionParameter = id_funcion.HasValue ?
                new ObjectParameter("Id_funcion", id_funcion) :
                new ObjectParameter("Id_funcion", typeof(int));
    
            var id_salaParameter = id_sala.HasValue ?
                new ObjectParameter("Id_sala", id_sala) :
                new ObjectParameter("Id_sala", typeof(int));
    
            var descripcion_peliculaParameter = descripcion_pelicula != null ?
                new ObjectParameter("descripcion_pelicula", descripcion_pelicula) :
                new ObjectParameter("descripcion_pelicula", typeof(string));
    
            var fechaDispIniParameter = fechaDispIni.HasValue ?
                new ObjectParameter("FechaDispIni", fechaDispIni) :
                new ObjectParameter("FechaDispIni", typeof(System.DateTime));
    
            var fechaDispFinParameter = fechaDispFin.HasValue ?
                new ObjectParameter("FechaDispFin", fechaDispFin) :
                new ObjectParameter("FechaDispFin", typeof(System.DateTime));
    
            var precio_unitParameter = precio_unit.HasValue ?
                new ObjectParameter("precio_unit", precio_unit) :
                new ObjectParameter("precio_unit", typeof(double));
    
            var noReg_CarteleraParameter = noReg_Cartelera.HasValue ?
                new ObjectParameter("NoReg_Cartelera", noReg_Cartelera) :
                new ObjectParameter("NoReg_Cartelera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ERegCartelera", fecharegParameter, id_funcionParameter, id_salaParameter, descripcion_peliculaParameter, fechaDispIniParameter, fechaDispFinParameter, precio_unitParameter, noReg_CarteleraParameter);
        }
    
        public virtual int IRegCartelera(Nullable<System.DateTime> fechareg, Nullable<int> id_funcion, Nullable<int> id_sala, string descripcion_pelicula, Nullable<System.DateTime> fechaDispIni, Nullable<System.DateTime> fechaDispFin, Nullable<double> precio_unit, Nullable<int> noReg_Cartelera)
        {
            var fecharegParameter = fechareg.HasValue ?
                new ObjectParameter("Fechareg", fechareg) :
                new ObjectParameter("Fechareg", typeof(System.DateTime));
    
            var id_funcionParameter = id_funcion.HasValue ?
                new ObjectParameter("Id_funcion", id_funcion) :
                new ObjectParameter("Id_funcion", typeof(int));
    
            var id_salaParameter = id_sala.HasValue ?
                new ObjectParameter("Id_sala", id_sala) :
                new ObjectParameter("Id_sala", typeof(int));
    
            var descripcion_peliculaParameter = descripcion_pelicula != null ?
                new ObjectParameter("descripcion_pelicula", descripcion_pelicula) :
                new ObjectParameter("descripcion_pelicula", typeof(string));
    
            var fechaDispIniParameter = fechaDispIni.HasValue ?
                new ObjectParameter("FechaDispIni", fechaDispIni) :
                new ObjectParameter("FechaDispIni", typeof(System.DateTime));
    
            var fechaDispFinParameter = fechaDispFin.HasValue ?
                new ObjectParameter("FechaDispFin", fechaDispFin) :
                new ObjectParameter("FechaDispFin", typeof(System.DateTime));
    
            var precio_unitParameter = precio_unit.HasValue ?
                new ObjectParameter("precio_unit", precio_unit) :
                new ObjectParameter("precio_unit", typeof(double));
    
            var noReg_CarteleraParameter = noReg_Cartelera.HasValue ?
                new ObjectParameter("NoReg_Cartelera", noReg_Cartelera) :
                new ObjectParameter("NoReg_Cartelera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IRegCartelera", fecharegParameter, id_funcionParameter, id_salaParameter, descripcion_peliculaParameter, fechaDispIniParameter, fechaDispFinParameter, precio_unitParameter, noReg_CarteleraParameter);
        }
    
        public virtual int RegFact(string nom_pelicula, Nullable<int> cantidad_taq, string sala, Nullable<double> precio_unitario, Nullable<double> total)
        {
            var nom_peliculaParameter = nom_pelicula != null ?
                new ObjectParameter("Nom_pelicula", nom_pelicula) :
                new ObjectParameter("Nom_pelicula", typeof(string));
    
            var cantidad_taqParameter = cantidad_taq.HasValue ?
                new ObjectParameter("Cantidad_taq", cantidad_taq) :
                new ObjectParameter("Cantidad_taq", typeof(int));
    
            var salaParameter = sala != null ?
                new ObjectParameter("sala", sala) :
                new ObjectParameter("sala", typeof(string));
    
            var precio_unitarioParameter = precio_unitario.HasValue ?
                new ObjectParameter("precio_unitario", precio_unitario) :
                new ObjectParameter("precio_unitario", typeof(double));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegFact", nom_peliculaParameter, cantidad_taqParameter, salaParameter, precio_unitarioParameter, totalParameter);
        }
    
        public virtual ObjectResult<ShowCartelera_Result> ShowCartelera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowCartelera_Result>("ShowCartelera");
        }
    
        public virtual ObjectResult<ShowCarteleraxFun_Result> ShowCarteleraxFun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowCarteleraxFun_Result>("ShowCarteleraxFun");
        }
    
        public virtual ObjectResult<Showempleado_Result> Showempleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Showempleado_Result>("Showempleado");
        }
    
        public virtual ObjectResult<ShoweNom_Result> ShoweNom()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShoweNom_Result>("ShoweNom");
        }
    
        public virtual ObjectResult<ShowFun_Result> ShowFun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowFun_Result>("ShowFun");
        }
    
        public virtual ObjectResult<ShowSala_Result> ShowSala()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowSala_Result>("ShowSala");
        }
    
        public virtual ObjectResult<ShowTickets_Result> ShowTickets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowTickets_Result>("ShowTickets");
        }
    }
}
