//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuadre
    {
        public int Id_cuadre { get; set; }
        public Nullable<System.DateTime> fehca_cuadre { get; set; }
        public string user { get; set; }
        public int Id_factura { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Total_general { get; set; }
    }
}
