//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id_empleado { get; set; }
        public string Nombre_emp { get; set; }
        public string Apellido { get; set; }
        public int Id_sexo { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public int Id_horario { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public string Telefono { get; set; }
    }
}
