//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int No_factura { get; set; }
        public Nullable<System.DateTime> fecha_fact { get; set; }
        public Nullable<System.DateTime> fecha_valida { get; set; }
        public string Fun { get; set; }
        public string Descripcion_pelicula { get; set; }
        public string Sala { get; set; }
        public Nullable<double> precio_unit { get; set; }
        public Nullable<int> cantidad_taq { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> cant_ac { get; set; }
    }
}
