//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int No_fact { get; set; }
        public string Nom_pelicula { get; set; }
        public Nullable<int> Cantidad_taq { get; set; }
        public string sala { get; set; }
        public Nullable<double> precio_unitario { get; set; }
        public Nullable<double> total { get; set; }
    }
}
