//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public int Id_funcion { get; set; }
        public string descrip_fun { get; set; }
        public Nullable<System.TimeSpan> HoraIni { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
    }
}
