//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina_rrhh
    {
        public int Id_nomina { get; set; }
        public Nullable<System.DateTime> fecha_nomina { get; set; }
        public string Nombre_emp { get; set; }
        public string Nombre_apellidos { get; set; }
        public Nullable<double> sueldo_bruto { get; set; }
        public Nullable<double> afp { get; set; }
        public Nullable<double> ars { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> total_des { get; set; }
        public Nullable<double> sueldo_neto { get; set; }
    }
}
