//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id_usuario { get; set; }
        public string Usuario_idnom { get; set; }
        public string clave { get; set; }
        public string Tipo_usuario { get; set; }
        public int Id_empleado { get; set; }
    }
}
